name = "spectrum-dashboard"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
# Non-sensitive environment variables can go here

# KV namespace for storing historical data (30 days)
[[kv_namespaces]]
binding = "SPECTRUM_DATA"
id = "0069e2f3e7f6489c9781f7fcdad2c241"
preview_id = "9f5d258eea584b71a196523597254bd3"

# Secrets (set via wrangler secret put):
# - ACCOUNT_ID
# - ZONE_ID  
# - API_KEY
# - AUTH_EMAIL

[assets]
directory = "./public"
